apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: meetup-scraper-api
  name: meetup-scraper-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meetup-scraper-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meetup-scraper-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: registry.alexbissessur.dev/meetup-scraper-api:1.0
        name: meetup-scraper-api
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

        envFrom:
          - configMapRef:
              name: scraper-cfm

        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: MYSQL_USER

          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: MYSQL_PASSWORD

          - name: DATABASE_DATABASE
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: MYSQL_DATABASE

        resources: {}
status: {}
