apiVersion: batch/v1
kind: CronJob
metadata:
  name: cnmu-scraper
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cnmu-scraper
              image: registry.alexbissessur.dev/meetup-scraper:1.4
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: scraper-cfm

              env:
                - name: COMMUNITY
                  value: "cnmu"

                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: env-secret
                      key: MYSQL_USER

                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: env-secret
                      key: MYSQL_PASSWORD

                - name: DATABASE_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: env-secret
                      key: MYSQL_DATABASE

          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
