apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper
spec:
  schedule: "0 0 */2 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: meetup-scraper:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
