apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: meetup-scraper-api
  name: meetup-scraper-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: meetup-scraper-api
status:
  loadBalancer: {}
